server:
  port: 8080

spring:
  application:
    name: CodeMaster

  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: file:src/main/resources/templates/

  resources:
    static-locations: file:src/main/resources/static/
    cache:
      period: 0

  # Configuración de Base de Datos PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: titulacion
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  # create-drop para desarrollo, update para producción
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: America/Guayaquil